// vue2-nuxt2-js/pages/index.vue
<template>
  <div id="app">
    <LoginForm
      v-if="!isAuthed"
      :onLogin="handleLogin"
      :error-message="errorMessage"
    />
    <Welcome v-else :username="username" @logout="handleLogout" />
  </div>
</template>

<script>
import LoginForm from '../components/LoginForm.vue';
import Welcome from '../components/Welcome.vue';

export default {
  name: 'App',
  components: {
    LoginForm,
    Welcome,
  },
  data() {
    return {
      isAuthed: false,
      errorMessage: '',
      username: '',
    };
  },
  methods: {
    async handleLogin(creds) {
      try {
        this.errorMessage = '';
        const res = await fetch('/auth', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(creds),
        });
        if (res.status === 200) {
          this.isAuthed = true;
          this.username = creds.username;
        } else {
          if (res.status === 401) {
            const { message } = await res.json();
            this.errorMessage = message;
          } else {
            throw new Error(`error during auth, status code: ${res.status}`);
          }
        }
      } catch (e) {
        console.error(e);
      }
    },
    handleLogout() {
      this.isAuthed = false;
      this.username = '';
    },
  },
};
</script>

// react-next12-ts/pages/index.tsx
import type { NextPage } from 'next';
import { useState } from 'react';
import LoginForm from '../components/LoginForm';
import Welcome from '../components/Welcome';

const Home: NextPage = () => {
  const [isAuthed, setIsAuthed] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [username, setUsername] = useState('');

  const handleLogin = async (creds: { username: string; password: string }) => {
    try {
      setErrorMessage('');
      const res = await fetch('/auth', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(creds),
      });
      if (res.status === 200) {
        setIsAuthed(true);
        setUsername(creds.username);
      } else {
        if (res.status === 401) {
          const { message } = await res.json();
          setErrorMessage(message);
        } else {
          throw Error(`error during auth, status code: ${res.status}`);
        }
      }
    } catch (e) {
      console.error(e);
    }
  };

  return (
    <div className="lg:container lg mx-auto m-10">
      {isAuthed ? (
        <Welcome
          username={username}
          onLogout={() => {
            setIsAuthed(false);
            setUsername('');
          }}
        />
      ) : (
        <LoginForm onLogin={handleLogin} errorMessage={errorMessage} />
      )}
    </div>
  );
};

export default Home;
