// react-next12-ts/components/InputField.tsx
import React from 'react';

interface InputFieldProps
  extends React.DetailedHTMLProps<
      React.InputHTMLAttributes<HTMLInputElement>,
      HTMLInputElement
    >,
    React.AriaAttributes {
  name: string;
  label: string;
  submitted: boolean;
  requiredMessage: string;
}

const InputField: React.FC<InputFieldProps> = (props) => {
  const { className, label, submitted, requiredMessage, ...inputProps } = props;
  return (
    <label className="flex flex-col text-lg text-gray-800 mb-2">
      {label}:
      <input
        className={`p-2 text-gray-500 focus:outline-none border-2 ${className}`}
        {...inputProps}
      />
      {submitted && !inputProps.value && (
        <span className="text-red-500 mt-2">{requiredMessage}</span>
      )}
    </label>
  );
};

export default InputField;

// svelte-vite-ts/src/lib/InputField.svelte
<script lang="ts">
  export let label: string;
  export let submitted: boolean;
  export let requiredMessage: string;
  export let value: string;

  function handleInput(e: any) {
    value = e.target.value;
  }
</script>

<label class="flex flex-col text-lg text-gray-800 mb-2">
  {label}:
  <input
    {...$$restProps}
    {value}
    class="p-2 text-gray-500 focus:outline-none border-2"
    on:input={handleInput}
  />
  {#if submitted && !value}
    <span class="text-red-500 mt-2">
      {requiredMessage}
    </span>
  {/if}
</label>
