// vue2-cli4-js/src/components/InputField.vue
<template>
  <label class="flex flex-col text-lg text-gray-800 mb-2">
    {{ label }}:
    <input
      v-bind="$attrs"
      class="p-2 text-gray-500 focus:outline-none border-2"
      :value="value"
      @input="handleChange"
    />
    <span class="text-red-500 mt-2" v-if="submitted && !value">{{
      requiredMessage
    }}</span>
  </label>
</template>

<script>
export default {
  inheritAttrs: false,
  props: {
    label: String,
    submitted: Boolean,
    requiredMessage: String,
    value: String,
  },
  methods: {
    handleChange(event) {
      this.$emit('input', event.target.value);
    },
  },
};
</script>

// svelte-vite-ts/src/lib/InputField.svelte
<script lang="ts">
  export let label: string;
  export let submitted: boolean;
  export let requiredMessage: string;
  export let value: string;

  function handleInput(e: any) {
    value = e.target.value;
  }
</script>

<label class="flex flex-col text-lg text-gray-800 mb-2">
  {label}:
  <input
    {...$$restProps}
    {value}
    class="p-2 text-gray-500 focus:outline-none border-2"
    on:input={handleInput}
  />
  {#if submitted && !value}
    <span class="text-red-500 mt-2">
      {requiredMessage}
    </span>
  {/if}
</label>
